# Generated by Django 3.2.4 on 2021-06-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Country',
        ),
    ]
